name: Auto sync helm chart

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-chart:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.12.0
      - name: Lint Helm Chart
        run: |
          for DIR in */ ; do
            if [ "$DIR" = ".github/" ]; then
              echo "Skipping .github directory"
              continue
            fi

            if [ -f "$DIR/Chart.yaml" ]; then
              echo "Linting Helm chart in directory: $DIR"
              helm dependency update "$DIR"
              helm lint "$DIR"
            else
              echo "Skipping $DIR (no Chart.yaml)"
            fi
          done
  sync-chart:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.12.0
      - name: Sync Helm Chart
        run: |
          for DIR in */ ; do
            if [ "$DIR" = ".github"]
            then
              echo "Skipping .github directory"
              continue
              echo "Packaging Helm chart in directory: $DIR"
              helm package "$DIR"
            fi
          helm repo index . --url https://chartmuseum.khiemnd.dev/
          done
      - name: Setup S3 credentials assume role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::359672545978:role/github-actions-role
          aws-region: ap-southeast-1
      - name: Sync to S3
        run: |
          aws s3 cp index.yaml s3://chartmuseum.khiemnd.dev/ --content-type "application/x-yaml" --metadata-directive REPLACE
          for f in *.tgz; do
          aws s3 cp "$f" "s3://chartmuseum-khiemnd-dev/$f" \
            --content-type "application/gzip" \
            --metadata-directive REPLACE
          done
          aws cloudfront create-invalidation --distribution-id E2QEXAMPLEC6M6Z --paths "/index.yaml" "/ *.tgz"

