name: Auto sync helm chart

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-chart:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.12.0
      - name: Lint Helm Chart
        run: |
          for DIR in */ ; do
            if [ "$DIR" = ".github/" ]; then
              continue
            fi

            if [ -f "$DIR/Chart.yaml" ]; then
              helm dependency update "$DIR"
              helm lint "$DIR"
            fi
          done

  sync-chart:
    permissions:
      id-token: write
      contents: read
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.12.0

      - name: Setup S3 credentials assume role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::359672545978:role/github-actions-role
          aws-region: ap-southeast-1

      - name: Download old index.yaml
        run: |
          aws s3 cp s3://chartmuseum-khiemnd-dev/index.yaml old-index.yaml || echo "no old index"

      - name: Package charts
        run: |
          for DIR in */ ; do
            if [ "$DIR" = ".github/" ]; then
              continue
            fi

            if [ -f "$DIR/Chart.yaml" ]; then
              helm dependency update "$DIR"
              helm package "$DIR"
            fi
          done

      - name: Build & merge index.yaml
        run: |
          # Nếu có index cũ thì merge
          if [ -f old-index.yaml ]; then
            helm repo index . \
              --url https://chartmuseum.khiemnd.dev/ \
              --merge old-index.yaml
          else
            helm repo index . \
              --url https://chartmuseum.khiemnd.dev/
          fi

      - name: Upload to S3
        run: |
          aws s3 cp index.yaml s3://chartmuseum-khiemnd-dev/ \
            --content-type "application/x-yaml" --metadata-directive REPLACE

          for f in *.tgz; do
            aws s3 cp "$f" "s3://chartmuseum-khiemnd-dev/$f" \
              --content-type "application/gzip" \
              --metadata-directive REPLACE
          done

          aws cloudfront create-invalidation \
            --distribution-id E2HBWOC1NX2JN9 \
            --paths "/*"
